# Generated by Django 2.2 on 2019-04-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_author_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
